spring:
  application:
    name: stock-manager

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://localhost:5432/stock-manager
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days


